services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - 8000
    env_file:
      - ../.env
    volumes:
      - ../backend/pong_service:/app/pong_service
      - ../backend/logs:/app/logs
      - ../backend/config:/app/config
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - ../.env
    ports:
      - '5432:5432'

  nginx:
    image: nginx:1.27
    volumes:
      - ../frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend:/usr/share/nginx/html
    ports:
      - '8081:8081'
    depends_on:
      - backend