services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - '6379:6379'

  backend:
    restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - 8000
    env_file:
      - ../.env
    volumes:
      - ../backend/pong_service:/app/pong_service
      - ../backend/logs:/app/logs
      - ../backend/config:/app/config
    depends_on:
      - postgres

  websocket:
    restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 --access-log - --verbosity 2 pong_service.asgi:application
    expose:
      - 8001
    env_file:
      - ../.env
    volumes:
      - ../backend/pong_service:/app/pong_service
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27
    restart: always
    volumes:
      - ../frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend:/usr/share/nginx/html
    ports:
      - '8081:8081'
    depends_on:
      - backend
      - websocket

volumes:
  postgres_data: